config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Routes for the 'Recipes'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member

    # Routes for the 'Recipe Foods'
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  # Defines the route for the "foods"
  resources :foods, only: [:index, :new, :create, :destroy]

  #Route for the 'Public Recipes' page
  get '/public_recipes', to: 'recipe_foods#index', as: 'public_recipes'

  # Route for the 'General shopping list' page
  get '/general_shopping_list', to: 'recipe_foods#general_shopping_list', as: 'general_shopping_list'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # before_validation :convert_hours_to_minutes
  belongs_to :user
  has_and_belongs_to_many :foods, join_table: 'recipe_foods'
  has_many :recipe_foods, dependent: :destroy

  # Validations.
  validates :name, :description, presence: true
  validates :name, length: { maximum: 250 }
  validates :preparation_time, :cooking_time, presence: true, comparison: { greater_than_or_equal_to: 0 },
                                              numericality: { only_integer: true }
  validates :public, inclusion: { in: [true, false] }

  def total_price
    recipe_foods.includes(:food).sum { |recipe_food| recipe_food.food.price * recipe_food.quantity }
  end

  def count_ingredients
    foods.count
  end

  def convert_hours_to_minutes
    self.preparation_time = (preparation_time.to_f * 60).to_i
    self.cooking_time = (cooking_time.to_f * 60).to_i
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
	def index
		@user = current_user
		@recipes = Recipe.where(user_id: @user.id)
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create update_status destroy]
  before_action :recipe_by_user, only: %i[index new create destroy]

  def index
    @recipes = current_user.recipes.all
  end

  def new
    @recipe = @recipe.new
  end

  def create
    recipe = @recipe.new(recipe_params)
    render :new unless recipe.save
    flash[:notice] = 'The Recipe was created successfully!'
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
    if can? :read, @recipe
      render :show
    else
      flash[:alert] = 'This recipe does not exist!'
      redirect_to public_recipes_path unless user_signed_in?
      redirect_to recipes_path if user_signed_in?
    end
  end

  def update_status
    recipe = Recipe.find(params[:id])
    status = recipe.public ? false : true
    recipe.update(public: status)
    redirect_to recipe_path(recipe)
  end

  def destroy
    recipe = @recipe.find(params[:id])
    if recipe.destroy
      flash[:notice] = 'The Recipe was deleted successfully!'
    else
      flash[:alert] = 'The Recipe was not deleted!'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    # Convert the hours into minutes.
    params[:recipe][:preparation_time] = (params[:recipe][:preparation_time].to_f * 60).to_i
    params[:recipe][:cooking_time] = (params[:recipe][:cooking_time].to_f * 60).to_i

    # Require parameters
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end

  def recipe_by_user
    @recipe = current_user.recipes
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper
  def to_hour(value)
    result = (value / 60)
    return "#{result} #{'hour'.pluralize(result)}" if value.to_i.remainder(60).zero?

    result = (value.to_i.to_f / 60).to_f.round(2)
    "#{result} #{'hour'.pluralize(result)}"
  end
end

app/views/recipes/index.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
	<div class="recipes-container d-flex flex-column align-items-center justify-center">

		<h1 class="main-title">Recipes List</h1>

		<div class="button-wrapper d-flex align-items-center">
			<%= link_to 'Add Recipe', new_recipe_path, class: 'btn primary-bg primary-text primary-border' %>
		</div>

		<% @recipes.each do |recipe| %>
			<div class="recipes">
				<div class="recipes-title d-flex flex-column align-items-center">
					<%= link_to recipe_path(recipe), class: 'dark-text' do %>
						<h2><%= recipe.name %></h2>
					<% end %>
					<%= link_to 'Remove', recipe_path(recipe), data: { turbo_method: :delete }, class: 'btn danger-bg danger-text danger-border' %>
				</div>
				<p><%= recipe.description.truncate(100) %></p>
			</div>
		<% end %>
	</div>
</section>

app/views/recipes/new.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="section-container d-flex flex-column align-items-center">

    <h1 class="main-title">Create a new Recipe</h1>

    <div class="form-wrapper">
      <%= form_with(model: @recipe, url: recipes_path) do |f| %>
        <div class="form-fields-group">
          <%= f.label :name %>
          <%= f.text_field :name, required: true, class: 'form-field' %>
        </div>
        <div class="form-fields-group">
          <%= f.label 'Preparation time (hours):' %>
          <%= f.number_field :preparation_time, min: 0, step: 0.01, required: true, class: 'form-field' %>
        </div>
        <div class="form-fields-group">
          <%= f.label 'Cooking time (hours):' %>
          <%= f.number_field :cooking_time,  min: 0, step: 0.01, required: true, class: 'form-field' %>
        </div>
        <div class="form-fields-group">
          <div class="gap-0_7 d-flex flex-row">
            <%= f.radio_button :public, true, class: 'radio-buttons' %>
            <%= f.label 'Public' %>
          </div>
          <div class="gap-0_7 d-flex flex-row">
            <%= f.radio_button :public, false, class: 'radio-buttons' %>
            <%= f.label 'Private' %>
          </div>
        </div>
        <div class="form-fields-group" id="recipe-description">
          <%= f.label :description %>
          <%= f.text_area :description, required: true, class: 'form-field' %>
        </div>
        <div class="actions w-100 d-flex flex-row justify-end align-items-center">
          <%= f.submit "Save recipe", class: 'btn primary-bg primary-text primary-border' %>
          <%= link_to 'Cancel', recipes_path, class: 'btn warning-bg warning-text warning-border' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="section-container d-flex flex-column align-items-center">
    <h1 class="main-title"><%= @recipe.name %></h1>
    <div class="w-100">

      <div class="container_col-2 between">
        <h2 class="subtitle">Preparation Time: <%= to_hour(@recipe.preparation_time) %></h2>
        <%= render partial: 'partials/public_toggle_button', object: @recipe, as: :recipe %>
      </div>

      <h2 class="subtitle">Cooking Time: <%= to_hour(@recipe.cooking_time) %></h2>
      <h2 class="subtitle">Description:</h2>
      <p class="main-text"><%= @recipe.description %></p>

      <% if can? :manage, @recipe %>
        <div class="container_col-2 between">
          <%= link_to 'Generate shopping list', general_shopping_list_path, class: 'btn primary-bg primary-text primary-border' %>
          <%= link_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn primary-bg primary-text primary-border' %>
        </div>

        <table class="table">
          <thead class="table-header">
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Value</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody class="table-body">
            <%= render partial: 'partials/table_recipe_foods_item', collection: @recipe.recipe_foods.includes(:food), as: :recipe_food %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</section>