config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Routes for the 'Recipes'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member

    # Routes for the 'Recipe Foods'
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  # Defines the route for the "foods"
  resources :foods, only: [:index, :new, :create, :destroy]

  #Route for the 'Public Recipes' page
  get '/public_recipes', to: 'recipe_foods#index', as: 'public_recipes'

  # Route for the 'General shopping list' page
  get '/general_shopping_list', to: 'recipe_foods#general_shopping_list', as: 'general_shopping_list'
end

app/views/partials/_navbar.html.erb
<nav class="w-100">
  <ul class="menu d-flex flex-wrap justify-between align-items-center">
    <li class="logo"><%= link_to 'easyCOOK', root_path, class: 'light-text' %></li>
    <li class="nav-item"><%= link_to 'Home', root_path, class: 'light-text' %></li>
    <li class="nav-item"><%= link_to 'Public Recipes', public_recipes_path, class: 'light-text' %></li>

    <% if user_signed_in? %>
      <li class="nav-item"><%= link_to 'Foods', foods_path, class: 'light-text' %></li>
      <li class="nav-item"><%= link_to 'Recipes', recipes_path, class: 'light-text' %></li>
      <li class="nav-item session-link"><%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete } %></li>      
    <% else %>
      <li class="nav-item session-link"><%= link_to 'Sign In', new_user_session_path %></li>
      <li class="nav-item session-link muted"><%= link_to 'Sign Up', new_user_registration_path %></li>
    <% end %>

    <li class="toggle"><button type="button"><i class="fas fa-bars"></i></button></li>
  </ul>
</nav>

app/views/partials/_public_toggle_button.html.erb
<% if can? :manage, recipe %>
  <div>
    <%= turbo_frame_tag "Public" do %>
      <%= button_to update_status_recipe_path(recipe), method: :patch, class: 'toggle-button' do %>
        <span class="toggle-button-title">Public</span> 
        <span class="toggle-button__label <%= 'is_public' if recipe.public %>"></span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/partials/_table_food_item.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td>$<%= food.price %></td>
  <td><%= food.quantity %></td>
  <td>
    <%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: 'btn-inline danger-text', remote: true %>
  </td>
</tr>

app/views/partials/_table_general_shopping_list.html.erb
<tr>
	<td><%= ingredient.name %></td>
	<td><%= "#{ingredient.total_food} #{ingredient.measurement_unit}" %></td>
	<td><%= "$#{ingredient.general_price}" %></td>
</tr>

app/views/partials/_table_recipe_foods_item.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= "#{recipe_food.quantity}#{get_measurement_prefix(recipe_food.food.measurement_unit)}" %></td>
  <td><%= "$#{recipe_food.total_price}" %></td>
  <td>
    <div class="container_col-2">
      <%= link_to 'Modify', edit_recipe_recipe_food_path(recipe_food.recipe, recipe_food), remote: true, class: "btn-inline info-text" %>
      <%= button_to 'Remove', recipe_recipe_food_path(recipe_food.recipe, recipe_food), method: :delete, remote: true, class: 'btn-inline danger-text' %>
    </div>
  </td>
</tr>