config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Routes for the 'Recipes'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member

    # Routes for the 'Recipe Foods'
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  # Defines the route for the "foods"
  resources :foods, only: [:index, :new, :create, :destroy]

  #Route for the 'Public Recipes' page
  get '/public_recipes', to: 'recipe_foods#index', as: 'public_recipes'

  # Route for the 'General shopping list' page
  get '/general_shopping_list', to: 'recipe_foods#general_shopping_list', as: 'general_shopping_list'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :recipes, join_table: 'recipe_foods'
  has_many :recipe_foods, dependent: :destroy

  # validations
  validates :name, :measurement_unit, :price, :quantity, presence: true
  validates :name, length: { maximum: 150 }
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }

  def name_with_measurement_unit
    "#{name} (#{measurement_unit})"
  end

  # Method to calculate the total food in all the recipes without the existing food of the user.
  def general_food_quantity
    recipe_foods.joins(:food).sum('recipe_foods.quantity')
  end

  def total_food
    (general_food_quantity - quantity).abs
  end

  # Method to calculate the total price of an ingredient.
  def general_price
    total_food * price
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]
  before_action :food_by_user, only: %i[index new create destroy]

  def index
    @foods = current_user.foods.all
  end

  def new
    @food = @food.new
  end

  def create
    food = @food.new(food_params)
    render :new unless food.save
    flash[:notice] = 'The Food was created successfully!'
    redirect_to foods_path
  end

  def destroy
    food = @food.find(params[:id])
    if food.destroy
      flash[:notice] = 'The Food was deleted successfully!'
    else
      flash[:alert] = 'The Food was not deleted!'
    end
    redirect_to foods_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end

  def food_by_user
    @food = current_user.foods
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
  def get_measurement_prefix(measurement)
    options = {
      'grams' => 'g',
      'milliliters' => 'ml',
      'units' => 'units'
    }
    options[measurement]
  end
end

app/views/foods/index.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="section-container d-flex flex-column align-items-center">

    <h1 class="main-title">Foods List</h1>

    <div class="w-100">
      <div class="button-wrapper d-flex align-items-center">
        <%= link_to 'Add Food', new_food_path, class: 'btn primary-bg primary-text primary-border' %>
      </div>
      <table class="table">
        <thead class="table-header">
          <tr>
            <th>Food</th>
            <th>Measurement unit</th>
            <th>Unit price</th>
            <th>Quantity</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody class="table-body">
          <%= render partial: 'partials/table_food_item', collection: @foods, as: :food %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/foods/new.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="section-container d-flex flex-column align-items-center">

    <h1 class="main-title">Create a new food</h1>

    <div class="form-wrapper col-2-form">
      <%= form_with(model: @food, url: foods_path) do |f| %>
        <div class="form-fields-group">
          <%= f.label :name %>
          <%= f.text_field :name, required: true, class: 'form-field' %>
        </div>
        <div class="form-fields-group">
          <%= f.label 'Measurement unit' %>
          <%= f.select :measurement_unit, options_for_select(['grams', 'milliliters', 'units']), { prompt: 'Select a  measurement' }, required: true, class: 'form-field' %>
        </div>
        <div class="form-fields-group">
          <%= f.label 'Unit price' %>
          <%= f.number_field :price, min: 0.01, step: 0.01, required: true, class: 'form-field' %>
        </div>
        <div class="form-fields-group">
          <%= f.label :quantity %>
          <%= f.number_field :quantity, required: true, class: 'form-field' %>
        </div>
        <div class="actions">
          <%= f.submit "Save food", class: 'btn primary-bg primary-text primary-border' %>
          <%= link_to 'Cancel', foods_path, class: 'btn warning-bg warning-text warning-border' %>
        </div>
      <% end %>
    </div>
  </div>
</section>