config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # Routes for the 'Recipes'
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member

    # Routes for the 'Recipe Foods'
    resources :recipe_foods, only: [:new, :create, :edit, :update, :destroy]
  end

  # Defines the route for the "foods"
  resources :foods, only: [:index, :new, :create, :destroy]

  #Route for the 'Public Recipes' page
  get '/public_recipes', to: 'recipe_foods#index', as: 'public_recipes'

  # Route for the 'General shopping list' page
  get '/general_shopping_list', to: 'recipe_foods#general_shopping_list', as: 'general_shopping_list'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe'
  belongs_to :food, class_name: 'Food'

  # Avoids duplicated ingredients in the same recipe, but allows the use of the same ingredients in different recipes.
  validates :food_id, uniqueness: { scope: :recipe_id }

  # methods
  def total_price
    (quantity * food.price).round(2)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!, only: %i[destroy]
  before_action :foods_by_recipe, except: %i[index general_shopping_list]

  def index
    @recipes = Recipe.includes(:user).where(public: true).order(created_at: :desc)
  end

  def new
    @recipe_food = @recipe_food.new
  end

  def create
    recipe_food = @recipe_food.new(recipe_food_params)
    if recipe_food.save
      flash[:notice] = 'The ingredient was added successfully!'
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = recipe_food.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  def edit
    @recipe_food = @recipe_food.find_by(id: params[:id])
  end

  def update
    recipe_food = @recipe_food.find_by(id: params[:id])

    if recipe_food.update(recipe_food_params)
      flash[:notice] = 'The ingredient was modified successfully!'
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = recipe_food.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])
    recipe = recipe_food.recipe
    if recipe_food.destroy
      flash[:notice] = 'The Food was remove successfully!'
    else
      flash[:alert] = 'The Food was not remove!'
    end
    redirect_to recipe_path(recipe)
  end

  def general_shopping_list
    # Select all the ingredients in the recipes, joined with all the foods allowed.
    @general_recipe_foods = current_user.foods.joins(:recipe_foods).distinct

    @foods = []
    # Save only the ingredients that are missing (more than you have).
    @general_recipe_foods.each do |food|
      @foods << food if food.general_food_quantity > food.quantity
    end

    # Find the total price.
    @total_general_price = @foods.sum(&:general_price)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end

  def foods_by_recipe
    @foods = current_user.foods.all
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @recipe_food = @recipe.recipe_foods
    # Select the foods that are not in the recipe.
    @foods_not_in_recipe = @foods.where.not(id: @recipe_food.pluck(:food_id))
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/edit.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="section-container d-flex flex-column align-items-center">

    <h1 class="main-title">Edit an ingredient</h1>

    <div class="form-wrapper col-2-form">
        <%= form_with(model: @recipe_food, url: recipe_recipe_food_path(@recipe, @recipe_food)) do |f| %>
          <div class="form-fields-group">
            <%= f.label 'Select your ingredient' %>
            <%= f.collection_select(:food_id, [@recipe_food.food], :id, :name_with_measurement_unit, {required: true}, {class: 'form-field'}) %>
          </div>
          <div class="form-fields-group">
            <%= f.label :quantity %>
            <%= f.number_field :quantity, min: 1, step: 1, value: @recipe_food.quantity, required: true, class: 'form-field' %>
          </div>
          <div class="actions w-100 d-flex flex-row justify-end align-items-center">
            <%= f.submit "Save ingredient", class: 'btn primary-bg primary-text primary-border' %>
            <%= link_to 'Cancel', recipe_path(@recipe), class: 'btn warning-bg warning-text warning-border' %>
          </div>
        <% end %>
    </div>
  </div>
</section>

app/views/recipe_foods/general_shopping_list.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="section-container d-flex flex-column align-items-center">

    <h1 class="main-title">Shopping List</h1>

    <div class="w-100">

      <div class="container_col-2 between">
        <h2 class="subtitle">Amount of food items to buy: <span class="primary-text"><%= @foods.length %></span></h2>
        <h2 class="subtitle">Total value of food needed: <span class="primary-text"><%= "$#{@total_general_price}" %></span></h2>
      </div>

        <table class="table">
          <thead class="table-header">
            <tr>
              <th>Food</th>
              <th>Quantity</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody class="table-body">
            <%= render partial: 'partials/table_general_shopping_list', collection: @foods, as: :ingredient %>
          </tbody>
        </table>
    </div>
  </div>
</section>

app/views/recipe_foods/index.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
	<div class="recipes-container d-flex flex-column align-items-center justify-center">

		<h1 class="main-title">Public Recipes</h1>

		<% @recipes.each do |recipe| %>
			<div class="recipes">
				<div class="recipes-title d-flex flex-column align-items-center">
					<%= link_to recipe_path(recipe), class: 'dark-text' do %>
						<h2><%= recipe.name %></h2>
					<% end %>
					<p>By: <%= recipe.user.name %></p>
				</div>
				<div class="recipes-items-price">
					<p>Total food items: <%= recipe.count_ingredients %></p>
					<p>Total price: $<%= recipe.total_price %></p>
				</div>
			</div>
		<% end %>

	</div>
</section>

app/views/recipe_foods/new.html.erb
<%= image_tag 'body-bg.png', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="section-container d-flex flex-column align-items-center">

    <h1 class="main-title">Add an ingredient</h1>

    <div class="form-wrapper col-2-form">
        <%= form_with(model: @recipe_food, url: recipe_recipe_foods_path(@recipe)) do |f| %>
          <div class="form-fields-group">
            <%= f.label 'Select your ingredient' %>
            <%= f.collection_select(:food_id, @foods_not_in_recipe, :id, :name_with_measurement_unit, {required: true}, {class: 'form-field'}) %>
          </div>
          <div class="form-fields-group">
            <%= f.label :quantity %>
            <%= f.number_field :quantity, min: 1, step: 1, value: 1, required: true, class: 'form-field' %>
          </div>
          <div class="actions w-100 d-flex flex-row justify-end align-items-center">
            <%= f.submit "Save ingredient", class: 'btn primary-bg primary-text primary-border' %>
            <%= link_to 'Cancel', recipe_path(@recipe), class: 'btn warning-bg warning-text warning-border' %>
          </div>
        <% end %>
    </div>
  </div>
</section>